import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import * as mongoose from 'mongoose';
import { User } from './user.schema';

/**
 * Schema to track the visit history of users to a client
 */
@Schema({
  timestamps: true,
})
export class VisitHistory {
  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: User.name })
  user: string | User;

  @Prop()
  clientId: string;

  createdAt: Date;
}

/**
 * Document to be accessed by the MongoDB collection
 */
export type VisitHistoryDocument = VisitHistory & mongoose.Document;

/**
 * Mongoose schema generated by the given class
 */
export const VisitHistorySchema = SchemaFactory.createForClass(VisitHistory);
